name: IG → Airtable sync

on:
  workflow_dispatch:        # 手動実行ボタン
  schedule:
    - cron: "20 * * * *"    # 毎時20分に実行（UTC）。JSTだと+9時間

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 依存パッケージがない場合でも通る。あれば package.json から入る
      - name: Install deps (if any)
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: Run sync script
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_POSTS }}   # ← HashtagPosts
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_TOKEN: ${{ secrets.IG_TOKEN }}
        run: node index.js
