name: IG → Airtable (hourly)

on:
  schedule:
    - cron: "15 * * * *"   # 毎時15分に実行
  workflow_dispatch: {}     # 手動実行もOK

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: node -v
      - run: node index.js
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_POSTS: ${{ secrets.AIRTABLE_TABLE_POSTS }}
          AIRTABLE_TABLE_TAGS: ${{ secrets.AIRTABLE_TABLE_TAGS }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_TOKEN: ${{ secrets.IG_TOKEN }}
